[auth]
username = "admin"
password = "1234"

[goto]
access_token = "YOUR_ACCESS_TOKEN"
account_key  = "YOUR_ACCOUNT_KEY"
base_url     = "https://api.goto.com"

[token]
client_id     = "YOUR_CLIENT_ID"
client_secret = "YOUR_CLIENT_SECRET"
refresh_token = "YOUR_REFRESH_TOKEN"
token_url     = "https://api.getgo.com/oauth/v2/token"
